name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Ensure this matches your branch name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Upload ALL files in the repository (including index.html)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: .  # Upload the entire repository

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2