name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # Make sure this matches deploy step
          path: |
            index.html
            assets/  # Include your CSS, JS, and image folders if applicable
            styles.css  # Add any additional files

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # Ensure this matches the uploaded artifact
